apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo
  namespace: tailscale-pi
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    nginx.org/client-max-body-size: 10000m
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
spec:
  tls:
  - hosts:
      - forgejo.lag0.com.br
      - git.lag0.com.br
    secretName: lag0-wildcard-certificate-secret
  rules:
  - host: forgejo.lag0.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgejo-egress
            port:
              number: 3000
  - host: git.lag0.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgejo-egress
            port:
              number: 3000
  ingressClassName: nginx