apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-pi
resources:
- pi-tailscale-namespace.yaml
- pi-agent-service-egress-proxy.yaml
- pi-flux-ui-service-egress-proxy.yaml
- pi-flux-ui-service-ingress.yaml
- seafile-egress-proxy.yaml
- ton-seafile-egress.yaml
- immich-egress-proxy.yaml
- immich-ingress.yaml
- id-egress-proxy.yaml
- id-ingress.yaml
- pi-nfs.yaml 
- gitea-egress-proxy.yaml
- gitea-ingress.yaml
- kavita-egress-proxy.yaml
- kavita-ingress.yaml
- forgejo-ingress.yaml
- forgejo-egress-proxy.yaml
- vaultwarden-egress.yaml
- vaultwarden-ingress.yaml