apiVersion: v1
kind: Service
metadata:
  name: s3-egress
  namespace: tailscale-pi
  annotations:
    tailscale.com/tailnet-fqdn: s3-s3-tailscale.giraffe-carp.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
  - protocol: TCP
    port: 9000