apiVersion: v1
kind: Service
metadata:
  name: rustfs-egress
  namespace: tailscale-pi
  annotations:
    tailscale.com/tailnet-fqdn: rustfs-rustfs-tailscale.giraffe-carp.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
  - protocol: TCP
    port: 9001