apiVersion: v1
kind: Service
metadata:
  name: s3-tailscale
  namespace: rustfs
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: rustfs
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: LoadBalancer
  loadBalancerClass: tailscale