---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gw-serviceentry.yaml
  - gw-virtualservice.yaml
  - nas-serviceentry.yaml
  - nas-virtualservice.yaml
  - proxmox-serviceentry.yaml
  - proxmox-virtualservice.yaml
  - proxmox-destinationrule.yaml
  # - s3-serviceentry.yaml
  # - s3-virtualservice.yaml
  # - minio-serviceentry.yaml
  # - minio-virtualservice.yaml