apiVersion: v1
kind: Service
metadata:
  name: gitea-tailscale
  namespace: gitea
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app.kubernetes.io/instance: gitea-release
    app.kubernetes.io/name: server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  loadBalancerClass: tailscale