kind: Service
apiVersion: v1
metadata:
  name: cs16-surf-1
  namespace: cs16-surf-1
  labels:
    app: cs16-surf-1
spec:
  type: ClusterIP
  selector:
    app: cs16-surf-1
  ports:
  - name: udp-27015
    port: 27015
    targetPort: 27015
    protocol: UDP
