apiVersion: v1
kind: Service
metadata:
  name: rustfs-tailscale
  namespace: rustfs
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app.kubernetes.io/instance: rustfs-release
    app.kubernetes.io/name: rustfs
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  loadBalancerClass: tailscale