apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
- namespace.yaml
- helm.yaml
- database
- pvc.yaml
- immich-ingress-ts.yaml
- virtualservice.yaml
# - cilium-network-policy.yaml