apiVersion: v1
kind: Service
metadata:
  name: kavita-tailscale
  namespace: kavita
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app.kubernetes.io/instance: kavita-release
    app.kubernetes.io/name: server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  loadBalancerClass: tailscale