apiVersion: v1
kind: Service
metadata:
  name: kavita-tailscale
  namespace: kavita
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: kavita
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  loadBalancerClass: tailscale