apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-postgres
  namespace: authelia
spec:
  # At the time of writing, authelia is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
  #imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba
  
  imageName: docker.io/postgres:16-alpine
  # A bug was reported in v0.3.0, which does not allow a replicated setup:
  # https://github.com/authelia-app/authelia-charts/issues/149#issuecomment-2559012759
  instances: 1

  # The "postgres" superuser is needed only for import and it can be deactivated after migration.
  enableSuperuserAccess: true
  # superuserSecret: authelia-superuser

  #postgresGID: 0
  #postgresUID: 0
  managed:
    roles:
      - name: authelia
        superuser: true
        login: true
        passwordSecret:
          name: authelia-secrets-ton

  bootstrap:
    initdb:
      database: authelia
      owner: authelia
  storage:
    size: 8Gi
    storageClass: large-storage
