apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwoot
resources:
  - namespace.yaml
  # - helm.yaml
  # - helm-valkey.yaml
  # - virtualservice.yaml
  # - oidc  # OIDC SSO Extension - remove to disable
  # - database
  # - pvc.yaml