apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
- namespace.yaml
# - helm.yaml
- instance.yaml
- ollama-external.yaml
- virtualservice.yaml
- ingress-ts.yaml
- networkpolicy.yaml
